# Generated by Django 6.0.2 on 2026-05-07 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое описание вашей цели', max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(help_text='Подробно опишите что вы ищете', verbose_name='Описание')),
                ('request_type', models.CharField(choices=[('games', '🎮 Games'), ('study', '📚 Study'), ('project', '💻 Project'), ('other', '🔧 Other')], default='games', max_length=20, verbose_name='Тип заявки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку чтобы скрыть заявку', verbose_name='Активна')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
